# Generated by Django 4.2.20 on 2025-03-28 09:01

from django.db import migrations

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_is_verified"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
