# Generated by Django 4.2.20 on 2025-03-27 08:55

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

import base.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    base.fields.UUIDField(
                        default=base.fields.uuidv7, editable=False, primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "verbose_name": "корзина",
                "verbose_name_plural": "корзины",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    base.fields.UUIDField(
                        default=base.fields.uuidv7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активно?")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("title", models.CharField(max_length=255, verbose_name="название")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    base.fields.UUIDField(
                        default=base.fields.uuidv7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активно?")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("title", models.CharField(max_length=255, verbose_name="название")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("description", models.TextField(blank=True, null=True, verbose_name="описание")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="цена")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="shop.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    base.fields.UUIDField(
                        default=base.fields.uuidv7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="итоговая цена")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("COMPLETED", "Completed"), ("CANCELED", "Canceled")],
                        default="PENDING",
                        max_length=15,
                        verbose_name="статус",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    base.fields.UUIDField(
                        default=base.fields.uuidv7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="количество")),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.cart", verbose_name="корзина"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.product", verbose_name="продукт"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(through="shop.CartItem", to="shop.product"),
        ),
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="пользователь"
            ),
        ),
    ]
