# Generated by Django 4.2.20 on 2025-03-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="category",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="product",
            managers=[],
        ),
    ]
